### ISSUE TITLE
性能评测

### ISSUE THREAD

**Issue by Shannen3206** [RUC-GSAI/Llama-3-SynE#2]
请问论文中Table 7和Table 8中TinyLlama的性能是用什么工具测的？我用opencompass评测，模型是[TinyLlama-1.1B-intermediate-step-1431k-3T](https://huggingface.co/TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T)，测出来MMLU、CEVAL、CMMLU和ARC性能差不多，但是HumanEval 1.22，MBPP 1.60，GaoKao测了MathQA CHE和BIO的问答题，性能都是0？
![image](https://github.com/user-attachments/assets/6ef9f019-627b-4584-9e79-bed291454f04)

**Comment by survivi** [comment]
[LLMBox](https://github.com/RUCAIBox/LLMBox).
